version: '3'

services:
  z23_project_tunnel_client:
    build:
      context: ./source
      dockerfile: ./source/client/dockerfile
    image: z23_project_tunnel_client
    networks:
      - z23_network
    init: true
    tty: true
    command:
      [
        "python",
        "./client/tunnel_client.py",
        "172.21.23.10",
        "12345",
        "172.21.23.9",
        "54321",
        "12345"
      ]

    container_name: z23_project_tunnel_client

  z23_project_tunnel_server:
    build:
      context: ./source
      dockerfile: ./source/server/dockerfile
    image: z23_project_tunnel_server
    networks:
      - z23_network
    init: true
    tty: true
    command:
      [
        "python",
        "./server/tunnel_server.py",
        "172.21.23.9",
        "12345",
        "172.21.23.10",
        "54321",
        "12345",
        "142.250.189.206",
        "80",
        "128"
      ]

    container_name: z23_project_tunnel_server

networks:
  z23_network:
    driver: bridge
