version: '3'

services:
  z23_project_tunnel_client:
    container_name: z23_project_tunnel_client
    build:
      context: ./source
      dockerfile: ./dockerfile
    image: z23_project_tunnel_client
    networks:
      - z23_network
    ports:
      - "2137:2137"
    init: true
    tty: true
    command:
      [
        "python",
        "/app/client/tunnel_client.py",
        "z23_project_tunnel_server",
        "54321",
        "0.0.0.0",
        "2137",
        "12345"
      ]
    volumes:
      - ./source:/app

  z23_project_tunnel_server:
    container_name: z23_project_tunnel_server
    build:
      context: ./source/
      dockerfile: ./dockerfile
    image: z23_project_tunnel_server
    networks:
      - z23_network
    init: true
    tty: true
    command:
      [
        "python",
        "/app/server/tunnel_server.py",
        "z23_project_tunnel_client",
        "12345",
        "0.0.0.0",
        "2137",
        "54321",
        "google.com",
        "80",
        "80"
      ]
    volumes:
      - ./source:/app

networks:
  z23_network:
    driver: bridge
