version: '3'

services:
  z23_project_tunnel_client:
    build:
      context: /source
      dockerfile: /source/compose/dockerfile
    image: z23_project_tunnel_client
    networks:
      - z23_network
    init: true
    tty: true
    command: [ "python", "/app/client/tunnel_client.py" ]
    volumes:
      - /source:/app

    container_name: z23_project_tunnel_client

  z23_project_tunnel_server:
    build:
      context: /source
      dockerfile: /source/compose/dockerfile
    image: z23_project_tunnel_server
    networks:
      - z23_network
    init: true
    tty: true
    command: [ "python", "/app/server/tunnel_server.py" ]
    volumes:
      - ./source:/app

    container_name: z23_project_tunnel_server

networks:
  z23_network:
    driver: bridge
